### ISSUE TITLE
Allow a user to add media file

### ISSUE THREAD

**Issue by MercyAngelin2000** [ravishnu60/chat#1]
Allow a user to upload image, If it is possible , allow a user to upload all type od media. If not restrict the user to upload only supported files

**Comment by ravishnu60** [comment]
Now user can add media files, Can u check and update the status

**Comment by MercyAngelin2000** [comment]
@ravishnu60 YOu should get review from me. I have the rights to close this issue, You should not do this, I forgive you this time alone. Let me check now and update you

**Comment by ravishnu60** [comment]
@MercyAngelin2000  unfortunately I clicked.

**Comment by MercyAngelin2000** [comment]
@ravishnu60 it's ok, Iam unable to send image by pressing enter button. Can you fix this, also need cancel button to close the zoom in image

**Comment by ravishnu60** [comment]
okkk
