### ISSUE TITLE
Allow a user to set wallpaper 

### ISSUE THREAD

**Issue by MercyAngelin2000** [ravishnu60/chat#3]
Allow a user to set wallpaper for specific chat

**Comment by ravishnu60** [comment]
Which means profile ?

**Comment by MercyAngelin2000** [comment]
@ravishnu60

> Which means profiles?


in the specific chat allow a user to set images in the background  .
Updating profile can be create as separate issue

**Comment by ravishnu60** [comment]
Can't set background images for each users, it take storage

**Comment by MercyAngelin2000** [comment]
@ravishnu60 Then it is fine.Closing the issue
